<h1>Regular Expression Notebook</h1><br>

<mark>
@Author: SharkChilli_zx<br>
@Date:2019
</mark>

In [4]:
import re

<h3>re.findall</h3>

> import re

> re.findall(pattern, string, flags=0)

Python 正则表达式 re.findall 方法能够**以列表的形式返回能匹配的子串**

<h4>findall查找全部r标识代表后面是正则的语句

In [5]:
regular_v1 = re.findall(
    r'docs', 'https://docs.pythondocs.org/3/whatsnew/3.6.html')
print(regular_v1)

['docs', 'docs']


<h4>符号^表示匹配以https开头的字符串

In [6]:
regular_v2 = re.findall(
    r'^https', 'https://docs.httpspython.org/3/whatsnew/3.6.html')
print(regular_v2)

['https']


<h4>用$符号表示以html结尾的字符串

In [7]:
regular_v3 = re.findall(
    r'html$', 'https://docs.pythonhtml.org/3/whatsnew/3.6.html')
print(regular_v3)

['html']


<h4>[...]匹配括号中的其中一个字符

In [8]:
regular_v4 = re.findall(
    r'[t,w]h', 'https://docs.python.org/3/whatsnew/3.6.html')
print(regular_v4)

['th', 'wh']


---
<h4>'d' & 'D'</h4>

* 'd' 用来匹配0到9之间的数,表示取数字0-9
* 'D' 返回除了数字以外的内容

In [9]:
regular_v5 = re.findall(
    r"\d", "https://docs.python.org/3/whatsnew/3.6.html")

regular_v6 = re.findall(
    r"\d\d\d", "https://docs.python.org/3/whatsnew/3.6.html/1234")

regular_v7 = re.findall(
    r"\D", "https://docs.python.org/3/whatsnew/3.6.html")

regular_v7_1 = re.findall(
    r"\D+", "https://docs.python.org/3/whatsnew/3.6.html")

print('v5:', regular_v5, 
      '\nv6:', regular_v6, 
      '\n', '*****', 
      '\nv7:', regular_v7, 
      '\nv7_1:', regular_v7_1)

v5: ['3', '3', '6'] 
v6: ['123'] 
 ***** 
v7: ['h', 't', 't', 'p', 's', ':', '/', '/', 'd', 'o', 'c', 's', '.', 'p', 'y', 't', 'h', 'o', 'n', '.', 'o', 'r', 'g', '/', '/', 'w', 'h', 'a', 't', 's', 'n', 'e', 'w', '/', '.', '.', 'h', 't', 'm', 'l'] 
v7_1: ['https://docs.python.org/', '/whatsnew/', '.', '.html']


---
<h4>'w' & 'W'</h4>

* 'w' 在正则里面代表匹配从小写a到z,大写A到Z，数字0到9
* “W” 在正则里面代表匹配除了字母与数字以外的特殊符号

In [10]:
regular_v8 = re.findall(
    r"\w", "https://docs.python.org/3/whatsnew/3.6.html")

regular_v8_1 = re.findall(
    r"\w+", "https://docs.python.org/3/whatsnew/3.6.html")

regular_v9 = re.findall(
    r"\W","https://docs.python.org/3/whatsnew/3.6.html")

regular_v9_1 = re.findall(
    r"\W+","https://docs.python.org/3/whatsnew/3.6.html")

print ('v8:', regular_v8, 
       '\nv8_1:', regular_v8_1, 
       '\nv9:', regular_v9, 
       '\nv9_1:', regular_v9_1)

v8: ['h', 't', 't', 'p', 's', 'd', 'o', 'c', 's', 'p', 'y', 't', 'h', 'o', 'n', 'o', 'r', 'g', '3', 'w', 'h', 'a', 't', 's', 'n', 'e', 'w', '3', '6', 'h', 't', 'm', 'l'] 
v8_1: ['https', 'docs', 'python', 'org', '3', 'whatsnew', '3', '6', 'html'] 
v9: [':', '/', '/', '.', '.', '/', '/', '/', '.', '.'] 
v9_1: ['://', '.', '.', '/', '/', '/', '.', '.']


---
<h4>'s' & 'S'</h4>

* 's' 匹配任何不可见的字符，包括空格，制表符，换页符等等
* 'S' 匹配任何可见的字符

In [15]:
string = '2345  3456  4567  5678'

regex_1 = re.compile('\w+\s+\w+')
regular_s1 = regex_1.findall(string)

print('s1:', regular_s1)

s1: ['2345  3456', '4567  5678']


---
<h4>当正则表达式中存在括号( )时</h4>

In [16]:
regex_2 = re.compile('(\w+)\s+\w+')
regular_s2 = regex_2.findall(string)

regex_3 = re.compile('((\w+)(\s+)\w+)')
regular_s3 = regex_3.findall(string)

print('\n*****Note*****',
      '\ns2:', regular_s2, 
      '\ns3:', regular_s3)


*****Note***** 
s2: ['2345', '4567'] 
s3: [('2345  3456', '2345', '  '), ('4567  5678', '4567', '  ')]


---
正则表达式中**有一个括号**时,其**输出的内容就是括号匹配到的内容**，而不是整个表达式所匹配到的结果.
但是整个正则表达式执行了！只不过只输出括号匹配到的内容.

在第一次匹配时跟没有括号时一样，匹配到 "2345  3456" ,只不过**只输出**(/w+)匹配到的结果 即"2345"，
第二次匹配同理从"4567" 开始，匹配到"4567  5678",但是还是只是输出"4567"

---
当正则表达式中**有两个括号**时，其输出是一个list中包含2个tuple

从输出的结果可以看出，有2个元组，每一个元组中有2个字符串: 其中第一个字符串"2345 3456"是**最外面的括号**输出的结果

第二个是里面括号(/w+)输出的结果 "2345", 第二个元组是第二次匹配的结果
